from pathlib import Path

path = Path('apps/cloud-api/src/payments/payment.service.ts')
text = path.read_text()
old = """    if (created.idempotentReplay) {\n      if (created.attempt.dispatch_started_at !== null && created.attempt.state === 'INITIATED') {\n        await this.applyTransition(created.attempt.id, {\n          target: 'UNKNOWN',\n          source: 'SYSTEM',\n          sourceId: 'replay-after-provider-dispatch',\n          reasonCode: 'DISPATCH_RESULT_NOT_DURABLE',\n          providerRequestId: created.attempt.provider_request_id,\n          providerReceiptReference: created.attempt.provider_receipt_reference,\n        });\n      }\n      return {\n        attempt: await this.snapshot(created.attempt.id),\n        idempotentReplay: true,\n      };\n    }\n"""
new = """    if (created.idempotentReplay) {\n      if (created.attempt.dispatch_started_at !== null) {\n        await this.markDispatchedInitiatedUnknownIfStillInitiated(created.attempt.id);\n      }\n      return {\n        attempt: await this.snapshot(created.attempt.id),\n        idempotentReplay: true,\n      };\n    }\n"""
assert old in text, 'idempotent replay block anchor not found'
text = text.replace(old, new, 1)
anchor = """  private async beginProviderDispatch(attemptId: string): Promise<boolean> {\n"""
method = """  private async markDispatchedInitiatedUnknownIfStillInitiated(attemptId: string): Promise<void> {\n    await this.database.transaction(async (client) => {\n      const current = await this.attemptWithClient(client, attemptId, true);\n      if (current.state !== 'INITIATED' || current.dispatch_started_at === null) return;\n      await client.query(\n        `UPDATE payment_attempt_state SET\n           state = 'UNKNOWN',\n           reconciliation_required = true,\n           next_query_at = CASE\n             WHEN $2::text IS NOT NULL THEN clock_timestamp() + interval '5 seconds'\n             ELSE NULL\n           END,\n           last_provider_error_code = 'DISPATCH_RESULT_NOT_DURABLE',\n           updated_at = clock_timestamp()\n         WHERE attempt_id = $1 AND state = 'INITIATED'`,\n        [attemptId, current.provider_request_id],\n      );\n      await client.query(\n        `INSERT INTO payment_attempt_transitions(\n           id, attempt_id, from_state, to_state, source, source_id, reason_code, occurred_at\n         ) VALUES ($1,$2,'INITIATED','UNKNOWN','SYSTEM','replay-after-provider-dispatch',\n                   'DISPATCH_RESULT_NOT_DURABLE',clock_timestamp())\n         ON CONFLICT (attempt_id, source, source_id) DO NOTHING`,\n        [randomUUID(), attemptId],\n      );\n    });\n  }\n\n"""
assert anchor in text, 'beginProviderDispatch anchor not found'
text = text.replace(anchor, method + anchor, 1)
path.write_text(text)
